#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Sparkly documentation build configuration file, created by
# sphinx-quickstart on Fri May 27 09:53:00 2022.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../..'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon']
napoleon_google_docstring = True
napoleon_numpy_docstring = True


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Sparkly'
copyright = '2022, Derek Paulsen'
author = 'Derek Paulsen'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# Version comes from the publish pipeline (docs/publish.sh sets DOCS_VERSION from
# the package's pyproject.toml) so the displayed + canonical version stays in sync
# with the URL path /sparkly/<version>/.
release = os.environ.get("DOCS_VERSION", "0.1.0")
version = release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# HTML output: Furo, MadMatcher brand (mirrors madmatcher-pro/docs/conf.py so the
# whole docs.madmatcher.ai site looks like one product).
html_baseurl = f"https://docs.madmatcher.ai/sparkly/{release}/"
html_theme = 'furo'
html_static_path = ['_static']
html_css_files = [
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;560;680;700&family=JetBrains+Mono:wght@400;500;600&display=swap",
    "custom.css",
]
html_title = "Sparkly API reference"
html_logo = "_static/logo-mark.svg"
html_favicon = "_static/logo-mark.svg"
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#c5050c",
        "color-brand-content": "#c5050c",
        "color-foreground-primary": "#1d1d1f",
        "color-background-primary": "#ffffff",
        "color-background-secondary": "#f6f6f7",
    },
    "dark_css_variables": {
        "color-brand-primary": "#c5050c",
        "color-brand-content": "#c5050c",
        "color-background-primary": "#161617",
        "color-background-secondary": "#1f1f21",
    },
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Sparklydoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Sparkly.tex', 'Sparkly Documentation',
     'Derek Paulsen', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'sparkly', 'Sparkly Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Sparkly', 'Sparkly Documentation',
     author, 'Sparkly', 'One line description of project.',
     'Miscellaneous'),
]



